package community.leaf.textchain.adventure;

import net.kyori.adventure.audience.Audience;
import net.kyori.adventure.identity.Identified;
import net.kyori.adventure.identity.Identity;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.ComponentLike;
import net.kyori.adventure.text.TextComponent;
import net.kyori.adventure.text.event.ClickEvent;
import net.kyori.adventure.text.event.HoverEvent;
import net.kyori.adventure.text.event.HoverEventSource;
import net.kyori.adventure.text.format.Style;
import net.kyori.adventure.text.format.TextColor;
import net.kyori.adventure.text.format.TextDecoration;
import net.kyori.adventure.util.RGBLike;
import pl.tlinkowski.annotation.basic.NullOr;

import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import java.util.function.Function;

/**
 * Abstract text chain.
 *
 * @param <C>   self-returning chain subtype
 *              (for method chaining)
 */
@SuppressWarnings({"unused", "UnusedReturnValue"})
public abstract class Chain<C extends Chain<C>> implements AudienceSender<C>, ComponentLike
{
    private final WrappedTextComponentBuilder builder;
    
    public Chain(WrappedTextComponentBuilder builder)
    {
        this.builder = Objects.requireNonNull(builder, "builder");
    }
    
    /**
     * Gets this chain's constructor so more
     * chains of the same type can be created
     * and operated on. If a subtype has more
     * required constructor arguments than
     * just the standard
     * {@link WrappedTextComponentBuilder},
     * simply pass those dependencies along.
     *
     * @return  a valid standard constructor
     *          for the chain's type
     */
    protected abstract ChainConstructor<C> getConstructor();
    
    /**
     * Process the input text by converting
     * it from a string into a text component.
     *
     * @param text  the input text
     * @return  a component generated by
     *          processing the input text
     */
    protected abstract TextComponent processText(String text);
    
    /**
     * {@code this}, but generic.
     * For generic method chaining.
     *
     * @return  self as the generic chain type
     */
    @SuppressWarnings("unchecked")
    protected final C self() { return (C) this; }
    
    /**
     * Gets the internal wrapped text component
     * builder that this chain manipulates.
     *
     * @return  this chain's internal wrapped builder
     */
    public final WrappedTextComponentBuilder getBuilder() { return builder; }
    
    /**
     * Builds the chain.
     *
     * @return  a text chain
     *
     * @see WrappedTextComponentBuilder#asComponent()
     */
    @Override
    public final TextComponent asComponent() { return builder.asComponent(); }
    
    /**
     * Builds the chain as a list of components.
     * Since chains inherently operate on a
     * component builder's {@code extra} (its
     * {@link Component#children() children}),
     * most chain elements should remain intact.
     * However, non-style aspects of this chain's
     * root component builder will be lost.
     *
     * <p><b>Note:</b> this method is inadequate
     * for item lore because it not only preserves
     * new line characters ({@code "\n"}), but
     * <i>every</i> child component is a distinct
     * list entry.</p>
     *
     * <p>For a more lore-friendly list, use
     * {@link #asComponentListSplitByNewLine()}
     * instead.</p>
     *
     * @return  the chain as a flattened list of
     *          components
     *
     * @see Components#flattenExtra(Component)
     */
    public final List<Component> asComponentList()
    {
        return Components.flattenExtra(asComponent());
    }
    
    /**
     * Builds the chain as a list of components
     * by combining components until a new line
     * component (containing only {@code "\n"})
     * is encountered. Since chains inherently
     * operate on a component builder's {@code extra}
     * (its {@link Component#children() children}),
     * most chain elements should remain intact.
     * However, non-style aspects of this chain's
     * root component builder will be lost.
     *
     * <p><b>Note:</b> to obtain new line
     * components, use the {@code next} methods
     * like: {@link #nextLine()}.</p>
     *
     * @return  the chain as a flattened list of
     *          components combined until a
     *          new line is encountered
     *
     * @see Components#flattenExtraSplitByNewLine(Component)
     */
    public final List<Component> asComponentListSplitByNewLine()
    {
        return Components.flattenExtraSplitByNewLine(asComponent());
    }
    
    /**
     * Provides the consumer with {@code this} chain.
     * Useful for applying modifications of some sort
     * to the chain.
     *
     * @param consumer  a consumer
     * @return  self (for method chaining)
     */
    public C apply(Consumer<? super C> consumer)
    {
        Objects.requireNonNull(consumer, "consumer");
        consumer.accept(self());
        return self();
    }
    
    /**
     * Maps {@code this} chain to something else.
     *
     * @param mapper    mapper function
     * @param <V>   value type
     * @return  resulting value of the mapper function
     */
    public <@NullOr V> V map(Function<? super C, V> mapper)
    {
        Objects.requireNonNull(mapper, "mapper");
        return mapper.apply(self());
    }
    
    /**
     * Provides the consumer with a chain that
     * operates on the <b>latest</b> chain
     * element's {@code extra} (its {@link
     * Component#children() children}). Use this
     * to create a <b>group</b> of chain elements
     * that will inherit the formatting and style
     * from the latest existing chain element
     * (or create one if none exist).
     *
     * @param consumer  extra consumer
     * @return  self (for method chaining)
     */
    public C extra(Consumer<? super C> consumer)
    {
        Objects.requireNonNull(consumer, "consumer");
        consumer.accept(getBuilder().peekOrCreateChild().wrap(getConstructor()));
        return self();
    }
    
    /**
     * Provides the consumer with a chain that
     * operates on a <b>new</b> chain element's
     * {@code extra} (its {@link Component#children()
     * children}). Use this to create a <b>group</b>
     * of chain elements that will inherit the
     * formatting and style from this new
     * chain element.
     *
     * @param consumer  extra consumer
     * @return  self (for method chaining)
     */
    public C thenExtra(Consumer<? super C> consumer)
    {
        Objects.requireNonNull(consumer, "consumer");
        consumer.accept(getBuilder().createNextChild().wrap(getConstructor()));
        return self();
    }
    
    /**
     * Creates a <b>new</b> chain element
     * containing the provided component-like.
     * If the component obtained from the argument
     * is a {@link TextComponent} instance, it
     * will be converted to a builder and added
     * as the next chain element. Otherwise, a new,
     * empty text component builder will be created
     * and the component will simply be appended to
     * it (as an {@code extra} child).
     *
     * @param componentLike the component-like
     *                      to append
     * @return  self (for method chaining)
     */
    public C then(ComponentLike componentLike)
    {
        Component component = Components.safelyAsComponent(componentLike);
        
        if (component instanceof TextComponent)
        {
            getBuilder().createNextChildWithBuilder(((TextComponent) component).toBuilder());
        }
        else
        {
            getBuilder().createNextChild().getComponentBuilder().append(component);
        }
        
        return self();
    }
    
    /**
     * Creates a <b>new</b> empty chain element.
     *
     * @return  self (for method chaining)
     */
    public C thenEmpty() { return then(Component.empty()); }
    
    /**
     * Creates a <b>new</b> chain element by
     * processing the input text with the
     * provided processor.
     *
     * @param text          the text to append
     * @param processor     text processor
     * @return  self (for method chaining)
     */
    public C then(String text, TextProcessor processor)
    {
        Objects.requireNonNull(text, "text");
        Objects.requireNonNull(processor, "processor");
        return then(processor.apply(text));
    }
    
    /**
     * Creates a <b>new</b> chain element by first
     * {@link #processText(String) processing} the
     * input text. Different chain types will
     * process the text differently. To skip
     * processing altogether, use {@link
     * #thenUnprocessed(String)}.
     *
     * @param text  the text to append
     * @return  self (for method chaining)
     */
    public C then(String text) { return then(text, this::processText); }
    
    /**
     * Creates a <b>new</b> chain element by
     * directly converting it to a new text
     * component, skipping processing entirely.
     *
     * @param text  the text to append
     * @return  self (for method chaining)
     */
    public C thenUnprocessed(String text) { return then(text, TextProcessor::none); }
    
    public C nextLine() { return then(Component.newline()); }
    
    public C next(ComponentLike componentLike) { return nextLine().then(componentLike); }
    
    public C next(String text, TextProcessor processor)
    {
        return nextLine().then(text, processor);
    }
    
    public C next(String text) { return nextLine().then(text); }
    
    public C nextUnprocessed(String text) { return nextLine().thenUnprocessed(text); }
    
    public C content(String text)
    {
        Objects.requireNonNull(text, "text");
        getBuilder().peekThenApply(child -> child.content(text));
        return self();
    }
    
    public C style(Style style)
    {
        Objects.requireNonNull(style, "style");
        getBuilder().peekThenApply(child -> child.style(style));
        return self();
    }
    
    public C unformatted() { return style(Components.UNFORMATTED); }
    
    public C color(TextColor color)
    {
        Objects.requireNonNull(color, "color");
        getBuilder().peekThenApply(child -> child.color(color));
        return self();
    }
    
    public C color(RGBLike rgb)
    {
        Objects.requireNonNull(rgb, "rgb");
        return color(TextColor.color(rgb));
    }
    
    public C format(TextDecoration decoration)
    {
        Objects.requireNonNull(decoration, "decoration");
        getBuilder().peekThenApply(child -> child.decorate(decoration));
        return self();
    }
    
    public C format(TextDecoration ... decorations)
    {
        Objects.requireNonNull(decorations, "decorations");
        getBuilder().peekThenApply(child -> child.decorate(decorations));
        return self();
    }
    
    public C format(TextDecoration decoration, boolean state)
    {
        Objects.requireNonNull(decoration, "decoration");
        getBuilder().peekThenApply(child -> child.decoration(decoration, state));
        return self();
    }
    
    public C format(TextDecoration decoration, TextDecoration.State state)
    {
        Objects.requireNonNull(decoration, "decoration");
        Objects.requireNonNull(state, "state");
        getBuilder().peekThenApply(child -> child.decoration(decoration, state));
        return self();
    }
    
    public C bold() { return format(TextDecoration.BOLD); }
    
    public C bold(boolean state) { return format(TextDecoration.BOLD, state); }
    
    public C bold(TextDecoration.State state) { return format(TextDecoration.BOLD, state); }
    
    public C italic() { return format(TextDecoration.ITALIC); }
    
    public C italic(boolean state) { return format(TextDecoration.ITALIC, state); }
    
    public C italic(TextDecoration.State state) { return format(TextDecoration.ITALIC, state); }
    
    public C obfuscated() { return format(TextDecoration.OBFUSCATED); }
    
    public C obfuscated(boolean state) { return format(TextDecoration.OBFUSCATED, state); }
    
    public C obfuscated(TextDecoration.State state) { return format(TextDecoration.OBFUSCATED, state); }
    
    public C strikethrough() { return format(TextDecoration.STRIKETHROUGH); }
    
    public C strikethrough(boolean state) { return format(TextDecoration.STRIKETHROUGH, state); }
    
    public C strikethrough(TextDecoration.State state) { return format(TextDecoration.STRIKETHROUGH, state); }
    
    public C underlined() { return format(TextDecoration.UNDERLINED); }
    
    public C underlined(boolean state) { return format(TextDecoration.UNDERLINED, state); }
    
    public C underlined(TextDecoration.State state) { return format(TextDecoration.UNDERLINED, state); }
    
    public C click(ClickEvent event)
    {
        Objects.requireNonNull(event, "event");
        getBuilder().peekThenApply(child -> child.clickEvent(event));
        return self();
    }
    
    public C command(String command)
    {
        Objects.requireNonNull(command, "command");
        return click(ClickEvent.runCommand(command));
    }
    
    public C suggest(String suggestion)
    {
        Objects.requireNonNull(suggestion, "suggestion");
        return click(ClickEvent.suggestCommand(suggestion));
    }
    
    public C link(String link)
    {
        Objects.requireNonNull(link, "link");
        return click(ClickEvent.openUrl(link));
    }
    
    public C insertion(String insertion)
    {
        Objects.requireNonNull(insertion, "insertion");
        getBuilder().peekThenApply(child -> child.insertion(insertion));
        return self();
    }
    
    public C hover(HoverEventSource<?> eventSource)
    {
        Objects.requireNonNull(eventSource, "eventSource");
        getBuilder().peekThenApply(child -> child.hoverEvent(eventSource));
        return self();
    }
    
    public C tooltip(ComponentLike componentLike)
    {
        return hover(HoverEvent.showText(Components.safelyAsComponent(componentLike)));
    }
    
    public C tooltip(Consumer<? super C> tooltipConsumer)
    {
        Objects.requireNonNull(tooltipConsumer, "tooltipConsumer");
        C tooltipChain = getConstructor().apply(new WrappedTextComponentBuilder(Component.text()));
        tooltipConsumer.accept(tooltipChain);
        return tooltip(tooltipChain);
    }
    
    public C tooltip(String tooltipText, TextProcessor processor)
    {
        Objects.requireNonNull(tooltipText, "tooltipText");
        Objects.requireNonNull(processor, "processor");
        return tooltip(processor.apply(tooltipText));
    }
    
    public C tooltip(String tooltipText) { return tooltip(tooltipText, this::processText); }
    
    public C tooltipUnprocessed(String tooltipText) { return tooltip(tooltipText, TextProcessor::none); }
    
    @Override
    public C send(Audience audience)
    {
        audience.sendMessage(this);
        return self();
    }
    
    @Override
    public C send(Audience audience, Identity source)
    {
        audience.sendMessage(source, this);
        return self();
    }
    
    @Override
    public C send(Audience audience, Identified source)
    {
        audience.sendMessage(source, this);
        return self();
    }
    
    @Override
    public C actionBar(Audience audience)
    {
        audience.sendActionBar(this);
        return self();
    }
}
