main: community.leaf.textchain.examples.paper.TextChainExamplePaperPlugin
name: ${project.name}
version: ${revision}
api-version: 1.13

commands:
  textchain:
    aliases: [test-text-chain, testtextchain, ttc]
    permission: textchain.test
