main: community.leaf.examples.textchain.paper.TextChainExamplePaperPlugin
name: ${project.name}
version: ${revision}
api-version: 1.13

commands:
  textchainpaper:
    aliases: [test-text-chain-paper, testtextchainpaper, ttcp]
    permission: textchain.test
