main: community.leaf.examples.textchain.bukkit.TextChainExampleBukkitPlugin
name: ${project.name}
version: ${revision}
api-version: 1.13

commands:
  textchain:
    aliases: [test-text-chain, testtextchain, ttc]
    permission: textchain.test
