main: community.leaf.examples.textchain.bukkit.TextChainExampleBukkitPlugin
name: ${project.name}
version: ${revision}
api-version: 1.13

commands:
  textchainbukkit:
    aliases: [test-text-chain-bukkit, testtextchainbukkit, ttcb]
    permission: textchain.test
